---
language: node_js
node_js:
  - '8'
  - node

cache: yarn

install:
  - yarn install
  - yarn global add codecov

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script:
        - yarn coverage
        - codecov